version: "2"

run:
  concurrency: 4
  timeout: 20m
  tests: false
  modules-download-mode: readonly

output:
  sort-order:
    - linter
    - severity
    - file
  show-stats: true

issues:
  uniq-by-line: true
  exclude-generated: strict
  exclude-dirs:
    - vendor
    - third_party

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - errorlint
    - copyloopvar
    - exhaustive
    - forbidigo
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - govet
    - goheader
    - goprintffuncname
    - gosec
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    dogsled:
      max-blank-identifiers: 2
    dupl:
      threshold: 150
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - filippo.io/age
            - filippo.io/edwards25519
            - github.com/MakeNowJust/heredoc
            - github.com/Masterminds/semver
            - github.com/Masterminds/sprig
            - github.com/alessio/shellescape
            - github.com/awnumar/memguard
            - github.com/basgys/goxml2json
            - github.com/cloudflare/tableflip
            - github.com/dchest/uniuri
            - github.com/elastic
            - github.com/fatih/color
            - github.com/fatih/structs
            - github.com/fernet/fernet-go
            - github.com/go-akka/configuration
            - github.com/go-jose/go-jose
            - github.com/go-ozzo/ozzo-validation
            - github.com/go-zookeeper/zk
            - github.com/gobwas/glob
            - github.com/golang/mock
            - github.com/golang/protobuf
            - github.com/golang/snappy
            - github.com/google/cel-go
            - github.com/google/go-github
            - github.com/google/gops
            - github.com/gosimple/slug
            - github.com/hashicorp/consul
            - github.com/hashicorp/hcl
            - github.com/hashicorp/vault
            - github.com/iancoleman/strcase
            - github.com/imdario/mergo
            - github.com/jmespath/go-jmespath
            - github.com/klauspost/compress
            - github.com/magefile/mage
            - github.com/mcuadros/go-defaults
            - github.com/miscreant/miscreant.go
            - github.com/oklog/run
            - github.com/open-policy-agent/opa
            - github.com/opencontainers/go-digest
            - github.com/opencontainers/image-spec
            - github.com/ory/dockertest
            - github.com/pelletier/go-toml
            - github.com/pierrec/lz4
            - github.com/pkg/errors
            - github.com/psanford/memfs
            - github.com/sethvargo/go-diceware
            - github.com/sethvargo/go-password
            - github.com/skratchdot/open-golang
            - github.com/spf13/cobra
            - github.com/spf13/viper
            - github.com/ulikunitz/xz
            - github.com/xeipuuv/gojsonschema
            - github.com/zclconf/go-cty
            - gitlab.com/NebulousLabs/merkletree
            - go.etcd.io/etcd
            - go.step.sm/crypto
            - go.uber.org/zap
            - golang.org/x/crypto
            - golang.org/x/oauth2
            - golang.org/x/ssh
            - golang.org/x/sync
            - golang.org/x/sys
            - golang.org/x/term
            - google.golang.org/genproto
            - google.golang.org/grpc
            - google.golang.org/protobuf
            - gopkg.in/yaml.v3
            - oras.land/oras-go
            - sigs.k8s.io/yaml
            - zntr.io/paseto
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - fmt:.*
        - io/ioutil.Read.*
    exhaustive:
      check-generated: false
      default-signifies-exhaustive: false
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G115
    misspell:
      locale: US
    lll:
      line-length: 140
      tab-width: 1
    gocognit:
      min-complexity: 20
    goconst:
      min-len: 3
      min-occurrences: 3
    nestif:
      min-complexity: 4
    unused:
      exported-fields-are-used: false
    unparam:
      check-exported: false
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    funlen:
      lines: 100
      statements: 50
    gomodguard:
      blocked:
        modules:
          - github.com/BurntSushi/toml:
              recommendations:
                - github.com/pelletier/go-toml
    goheader:
      template: |-
        Licensed to Elasticsearch B.V. under one or more contributor
        license agreements. See the NOTICE file distributed with
        this work for additional information regarding copyright
        ownership. Elasticsearch B.V. licenses this file to you under
        the Apache License, Version 2.0 (the "License"); you may
        not use this file except in compliance with the License.
        You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing,
        software distributed under the License is distributed on an
        "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
        KIND, either express or implied.  See the License for the
        specific language governing permissions and limitations
        under the License.
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
        - opinionated
        - experimental
