app:
    production:
        database:
            user: app-CfOIkrHzHzrLVkDg
            password: LhV9!mtAuyvkES2w-EaXzM$eeZQP7}Jo0z0BIp6AUndGrM`FJ7}]_<y7CD3kBT{0
        server:
            privacy:
                principal: ZHVlfTk2RFVidk1rPmhIOEhpWTxlb2JTbSNcMU9TUnBPQDcsd0UzNjVjSjVOWDJXWyVxYnNUaVBxVndReWFnOg==
            http:
                session:
                    cookieKeyB64: Q2NvXlJ8bW5ddnN5amd8dllLWnlCdWNRcUM2MDE1Vlg1VWF3OTBuRmNHVyFvMil3eTo3e3hISmlpbCZaOFtOZg==
                token:
                    signingPrivateKeyJWK: |-
                        {"kty":"EC","kid":"wSVVjRQghnVpiBq_m-33x372CuS7cLonVO_IAKVUyXc=","crv":"P-384","x":"BxHLifJ_WA1SheahMCTXhMzXV8nXOiRiPRT_k73llHoKzrPRH4Sx5sR1_ouMVJtn","y":"ucMsK18nkVXNE4H4YbhzLbk7N8q7Zy2LjOfwhSajhF-YFfXPIFQFjDrDIAT6cnaX","d":"FdQ3cpbwseZEaGbanirmwfQLqN2J44R8xufqGrZDZbTOA4FZzsAX-NkEf_IZhTxc"}
                    signingPublicKeyJWK: |-
                        {"kty":"EC","kid":"wSVVjRQghnVpiBq_m-33x372CuS7cLonVO_IAKVUyXc=","crv":"P-384","x":"BxHLifJ_WA1SheahMCTXhMzXV8nXOiRiPRT_k73llHoKzrPRH4Sx5sR1_ouMVJtn","y":"ucMsK18nkVXNE4H4YbhzLbk7N8q7Zy2LjOfwhSajhF-YFfXPIFQFjDrDIAT6cnaX"}
        vendor:
            mailgun:
                apiKey: 1234567890



